name: flutter_snappyshop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  badges: ^3.1.2
  change_app_package_name: ^1.1.0
  dio: ^5.4.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  formz: ^0.6.1
  geolocator: ^11.0.0
  go_router: ^13.0.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.9.0
  reactive_forms: ^17.0.0
  rename_app: ^1.3.1
  shared_preferences: ^2.2.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#8034DA"
  # background_image: assets/icon/splash.png
  image: assets/icon/splash.png
  android_12:
    image: assets/icon/splash.png
    color: "#8034DA"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
